# Nécessite une cible UITest "vocabularyUITests" dans le projet Xcode.
devices(["iPhone 17 Pro Max", "iPhone 17"])
languages(["fr-FR"])
scheme("vocabularyUITests")
output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
launch_arguments(["-UITestMode YES"])
concurrent_simulators(false)
